-- Global Shefu V1 schema
-- Run this in Supabase SQL Editor.

create table if not exists public.puzzles (
  id text primary key,
  title text not null,
  secret_answer text not null,
  host_token text not null,
  created_at timestamptz not null default now(),
  status text not null default 'open' check (status in ('open', 'solved', 'closed'))
);

create table if not exists public.guesses (
  id bigint generated by default as identity primary key,
  puzzle_id text not null references public.puzzles(id) on delete cascade,
  guess_text text not null,
  is_correct boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists guesses_puzzle_id_created_at_idx
  on public.guesses (puzzle_id, created_at desc);

-- The V1 API uses the Supabase service-role key server-side.
-- Do NOT expose that key to the browser.
-- These tables can remain inaccessible to the anon role for this V1.
